#import  Category from "apps/categories/categories.schema.gql";
type Mutation {
    addCategory(
        name: String!,
        code: String!,
        representation:String,
        parent:String
    ):Category
}
